### ISSUE TITLE
The title of the Question should be used insted of "question_text"

### ISSUE THREAD

**Issue by miltontony** [praekelt/molo-ndoh-yep#16]
It's confusing at the moment to create a question because there are 2 fields "Title" and "Question Text". We should rather use "Title"

**Comment by miltontony** [comment]
Same for Choice - the Title should be used instead of 'Choice Text'

**Comment by smn** [comment]
@bruskiza where can we see these? Can you upload a screenshot & sample URL?

**Comment by bruskiza** [comment]
@smn this one logged by legendary @miltontony i'm afraid... i have trouble keeping up.

**Comment by smn** [comment]
I remember seeing changes for this in the code somewhere, did this already land in the rush on Friday morning?

**Comment by miltontony** [comment]
@smn resolved in this PR https://github.com/praekelt/molo-ndoh-yep/pull/29
PS: _sorry, github still sends to my personal email._
