### ISSUE TITLE
Markdown not working on production

### ISSUE THREAD

**Issue by bruskiza** [praekelt/molo-ndoh-yep#18]
Might want to note this one too- https://b-wise.mobi/english/your-peeps/bullying/abuse-when-somebody-hurts-another-person/ it’s displaying the markup i.e **abuse can be physical**, probably related to the cms bug.

**Comment by smn** [comment]
This is first & foremost a content issue. Lists items were being used instead of normal paragraphs. Markdown doesn't apply for list items, only for paragraph blocks that are added to the page.

Secondly, there's a CSS styling issue here. `<strong>` and related tags are stripped of their styling.

**Comment by smn** [comment]
@saeedmb8 can you check the styling issue here?

**Comment by smn** [comment]
Marking as resolved until we get clear feedback on what's not working. This ticket came from people who didn't understand well enough how the CMS works.
