### ISSUE TITLE
Latest section orders differently to the articles

### ISSUE THREAD

**Issue by bruskiza** [praekelt/molo-ndoh-yep#22]

**Comment by smn** [comment]
Looking at https://b-wise.mobi/english/mind-blowing/brain-freezzz/ this may have already been fixed? If this was a different issue please include a screenshot & URL. There's not enough context in this ticket to be actionable.

**Comment by smn** [comment]
@bruskiza please confirm if this was fixed or not?

**Comment by bruskiza** [comment]
Confirmed still a bug. https://www.tuneme.org/admin/pages/5/?ordering=ord

"Sex" section is listed above the "Relationships" section in the admin interface, and yet the order is not honoured on the home page.

**Comment by smn** [comment]
I'm not sure this is a bug to be honest. The listing there are all the articles that have been marked as "latest" ordered by their last publish date. The homepage isn't a section listing, it's an article listing and those are grouped according to their relevant sections (but the article is the leading object).

**Comment by smn** [comment]
Closing to get the number of issues down, please re-open if you feel this does need to be addressed somehow.
