### ISSUE TITLE
Confirm any embedded Featuring conventions you are aware of

### ISSUE THREAD

**Issue by bruskiza** [praekelt/molo-ndoh-yep#23]

**Comment by miltontony** [comment]
The order of featured articles on the homepage is based on the `first published date`, which is currently not editable. It was, but it broke some things, so we took it away. I'm looking for an alternative to making this field editable.

**Comment by smn** [comment]
Closing because there's not much actionable here. Please either re-open or create another ticket with details on the work needing to be done.
